<?php
// module/Album/view/album/album/index.phtml:

$title = $type==1?'Thêm kết quả Thi đua - Khen thưởng cho Cá nhân':'Thêm kết quả Thi đua - Khen thưởng cho Tập thể';
$this->headTitle($title);
?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
</div>
<?php
    $form->setAttribute('action',$this->url('commend',['action'=>'add','id'=>'1', 'type' => $type]));
    $form->prepare();
?>
<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('idCmd'));
?>
<br>
<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('idS'));
?>
<br>
<?php
    echo $this->formRow($form->get('idSubAward'));
?>
<br>
<?php
    echo $this->formRow($form->get('year'));
?>
<br>
<?php
    echo $this->formRow($form->get('nameQD'));
?>
<br>
<?php
    echo $this->formRow($form->get('submit'));
?>