<?php
// module/Album/view/album/album/index.phtml:

$title = 'Kết quả tìm kiếm cho "'.$searchtxt.'"' ;
$this->headTitle($title);
?>

<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
    

    <table id="example" class="table table-bordered dt-responsive " cellspacing="0" >
        <thead>
            <tr>
                <th>Tên cá nhân/tập thể</th>
                <th>Danh hiệu</th>
                <th>Danh Mục</th>
                <th>Năm</th>
                <th>Tên QĐ/ĐT/SK</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Tên cá nhân/tập thể</th>
                <th>Danh hiệu</th>
                <th>Danh Mục</th>
                <th>Năm</th>
                <th>Tên QĐ/ĐT/SK</th>
                <td></td>
            </tr>
        </tfoot>
        <tbody> 
        </tbody>
    </table>
    
    <script type="text/javascript">
        $(document).ready(function () {
            $('#example tfoot th').each(function () {
                var title = $(this).text();
                $(this).html('<input type="text" placeholder="Lọc: ' + title + '" />');
            });
            var table = $('#example').DataTable({
                "processing": true, // for show processing bar
                "orderMulti": false, // for disable multi column order

                "language": {
                    "lengthMenu": "Hiển thị _MENU_ bản ghi/trang",
                    "zeroRecords": "Không có thông tin",
                    "info": "Trang _PAGE_ / _PAGES_",
                    "infoEmpty": "Không có bản ghi nào để hiển thị",
                    "infoFiltered": "(Lọc từ _MAX_ bản ghi)",
                    "search": "Lọc nội dung",
                    "oPaginate": {
                        "sFirst": "<<", // This is the link to the first page
                        "sPrevious": "<", // This is the link to the previous page
                        "sNext": ">", // This is the link to the next page
                        "sLast": ">>" // This is the link to the last page
                    }

                },
                "ajax": {
                    "url": "/commend/listbytype/".$type,
                    "dataSrc": ""
                },
                "columns": [
                    {"data": getFullName},
                    {"data": "subAwardName"},
                    {"data": "awardName"},
                    {"data": "year", "width": "5%", "targets": 0 },
                    {"data": "nameQD"},
                    {"data": getBtn}
                ],
                "dom": '<"top"fiB>rt<"bottom"pl><"clear">',
                "buttons": [
                    {
                        extend: 'excelHtml5',
                        "text":'Xuất Excel',"className": 'btn btn-success btn-md btnexport',
                        exportOptions: {
                            columns: [0, 1, 2, 3,4]
                        },
                    },
                    {
                        extend: 'print',
                        "text":'Print',"className": 'btn btn-info btn-md',
                        exportOptions: {
                            columns: [0, 1, 2, 3,4]
                        },
                    },
                ]
            });

            table.columns().every(function () {
                var that = this;

                $('input', this.footer()).on('keyup change', function () {
                    if (that.search() !== this.value) {
                        that
                                .search(this.value)
                                .draw();
                    }
                });
            });

        });

        function getFullName(data, type, dataToSet) {
            var nameF;
            if (data.nameF == null) {
                nameF = "";
            } else {
                nameF = data.nameF;
            }
            return "<a href='/commend/detail/" + data.institute + "?id=" + data.idS + "'>" + nameF + " " + data.nameS + "</a>";
        }
        function getBtn(data, type, dataToSet) {
            return "<a class='btn btn-success' href='/commend/edit?type=" + data.institute + "&id=" + data.idCmd + "'>Sửa <span class='glyphicon glyphicon-edit'></span></a> | <a class='btn btn-danger' href='/commend/delete?id=" + data.idCmd + "' onclick='if (confirm(\"Bạn chắc chắn muốn xóa?\")) { document.location = this.href; } return false;' >Xóa <span class='glyphicon glyphicon-minus'></span></a>";
        }

    </script>