<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ARFM')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/jquery.dataTables.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->prependFile($this->basePath('js/myjs.js'))
                ->prependFile($this->basePath('js/jquery.dataTables.min.js'))
                ->prependFile($this->basePath('js/buttons.html5.min.js'))
        ?>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <!-- CSS for twitter bootstrap & datatable -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" >
        <!-- JS for twitter bootstrap & datatable -->
        <script type="text/javascript" src="hhttps://code.jquery.com/jquery-1.12.4.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
        
        
        
        <script type='text/javascript' src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
        <script type='text/javascript' src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>
        <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
        <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
        <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
        <script type='text/javascript' src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
        <script type='text/javascript' src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>

    </head>
    <body>
        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Quản lý thi đua - khen thưởng</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=
                    $this->url('commend', [
                        'action' => 'listbytype',
                        'id' => '1',
                    ])
                    ?>"><img src=""</a>
                    <a class="navbar-brand" href="#menu-toggle" id="menu-toggle"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
                    <a class="navbar-brand" href="<?=
                    $this->url('commend', [
                        'action' => 'listbytype',
                        'type' => '1',
                    ])
                    ?>">Quản lý thi đua khen thưởng</a>
                </div>
                <div class="container">
                    <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="<?= $this->url('logout') ?>"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> <?php
                                $user_session = new Zend\Session\Container('user');
                                $username = $user_session->acc;
                                echo $username;
                                ?></a></li>
                    </ul>
                    <form class="navbar-form navbar-right" action="\commend\search" method="GET">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Tìm kiếm cá nhân/tập thể theo tên" id="query" name="search" value="">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
                            </div>
                        </div>
                    </form>
                </div>
                </div>
            </div>
        </nav>
        <?php
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_ERROR, array('alert', 'alert-danger'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_INFO, array('alert', 'alert-info'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_SUCCESS, array('alert', 'alert-success'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_WARNING, array('alert', 'alert-warning'));
        echo $this->flashMessenger()->render(
                \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_DEFAULT, array('alert', 'alert-info'));
        ?> 
        <div id="wrapper" class="toggled">
            <div class="container-fluid">
                <!-- Sidebar -->
                <div id="sidebar-wrapper">
                    <ul class="sidebar-nav">
                        <li>
                            <a href="#" data-target="#item2" data-toggle="collapse"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Kết quả thi đua <span class="caret"></span></span></a>
                            <ul class="nav nav-stacked collapse" id="item2">
                                <li><a href="<?=
                                    $this->url('commend', [
                                        'action' => 'listbytype',
                                        'type' => '1',
                                    ])
                                    ?>">Cá nhân</a></li>
                                <li><a href="<?=
                                    $this->url('commend', [
                                        'action' => 'listbytype',
                                        'type' => '2',
                                    ])
                                    ?>">Tập thể</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?= $this->url('award') ?>"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> Quản lý danh mục </a>
                        </li>
                        <li>
                            <a href="#" data-target="#item3" data-toggle="collapse"><i class="fa fa-list"></i> <span class="collapse in hidden-xs"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Quản lý danh hiệu <span class="caret"></span></span></a>
                            <ul class="nav nav-stacked collapse" id="item3">
                                <?php foreach ($this->listSub as $award) { ?>
                                    <li>
                                        <a href="<?=
                                        $this->url('subaward', [
                                            'action' => 'index',
                                            'id' => $award->id,
                                        ])
                                        ?>"><?php echo $award->awardName; ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>              
                        <li>
                            <a href="#" data-target="#item4" data-toggle="collapse"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> Danh sách cá nhân/tập thể <span class="caret"></span></span></a>
                            <ul class="nav nav-stacked collapse" id="item4">
                                <li><a href="/subject/index?type=1">Cá nhân</a></li>
                                <li><a href="/subject/index?type=2"">Tập thể</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?= $this->url('auth') ?>"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Quản lý người dùng</a>
                        </li>

                    </ul>
                </div>
                <!-- /#sidebar-wrapper -->

                <!-- Page Content -->
                <div id="page-content-wrapper" style="padding-bottom: 100px;">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <?= $this->content ?>
                            </div>
                        </div>
                    </div>
                </div>



                <!-- /#page-content-wrapper -->
            </div>
        </div>
        <!-- /#wrapper -->

        <footer class="footer fixed-bottom">
            <div class="container">
                <p>&copy; <?= date('Y') ?> Quản lý Thi đua - Khen thưởng - CỤC TẦN SỐ VÔ TUYẾN ĐIỆN</p>
            </div>
        </footer>
        <?= $this->inlineScript() ?>
        
        <script>
            $("#menu-toggle").click(function (e) {
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
            });
        </script>
    </body>
</html>
