<?php
// module/Album/view/album/album/index.phtml:

$title = 'Thêm danh hiệu thi đua - khen thưởng thuộc danh mục' ;
$this->headTitle($title);
?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
</div>
<?php
    $form->setAttribute('action',$this->url('subaward',['action'=>'add']));
    $form->prepare();
?>

<?php
    echo $this->form()->openTag($form);
    
?>
<br>
<label>Tên danh hiệu thi đua - khen thưởng</label>
<?php
    echo $this->formRow($form->get('subAwardName'));
    
?>
<br>
<label>Loại danh mục</label>
<?php echo $this->formRow($form->get('awardId')); ?>
<br>
<label>Đối tượng</label>
<?php
    echo $this->formRow($form->get('institute'));
?>
<br>
<?php
    echo $this->formRow($form->get('submit'));
?>