<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Login')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body style="padding-top: 5px">
        <div class="container">
            <div class="row same-heigh">
                <div class="col-xs-12 col-sm-6 left same-heigh-col body-login" > 
                    <?php
                    $form->setAttribute('action', $this->url('login', ['action' => 'login']));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    ?>
                    <img style="margin: 0 auto;" src="<?= $this->basePath('img/logo.png') ?>" alt="" class="img-responsive" />
                    <div>
                        
                        <?php
                        echo $this->formRow($form->get('acc'));
                        ?>
                        <span class="glyphicon glyphicon-user"></span>
                    </div>

                    <div>
                        
                        <?php
                        echo $this->formRow($form->get('pass'));
                        ?>
                        <span class="glyphicon glyphicon-lock"></span>
                    </div>

                    <div>
                        <?php
                        echo $this->formRow($form->get('submit'));
                        ?>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>




                </div>
                <div class="hidden-xs col-sm-6 right same-heigh-col">
                    <img src="<?= $this->basePath('img/115TDH.jpg') ?>" class="img-responsive" alt="" style="width: 100%; max-height: 600px" />
                </div>
            </div>
        </div>
    </body>
    <html>