<?php
// module/Album/view/album/album/index.phtml:

$title = $type==1?'Thêm mới cá nhân':'Thêm mới tập thể';
$this->headTitle($title);
?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
<hr>
</div>
<?php
    $form->setAttribute('action',$this->url('subject',['action'=>'add']));
    $form->prepare();
?>

<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('nameF'));
?>
<br>
<?php
    echo $this->formRow($form->get('nameS'));
?>
<br>
<?php
    echo $this->formRow($form->get('email'));
?>
<br>
<?php
    echo $this->formRow($form->get('typeS'));
?>
<br>

<?php
    echo $this->formRow($form->get('submit'));
    
?>