<?php
// module/Album/view/album/album/index.phtml:

$title = 'Sửa thông tin cá nhân/tập thể';
$this->headTitle($title);
?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
</div>
<?php
    $form->setAttribute('action','/subject/edit?id='.$id);
    $form->prepare();
?>

<?php
echo $this->form()->openTag($form);
    echo $this->formRow($form->get('idS'));
?>
<br>
<?php
    
    echo $this->formRow($form->get('nameF'));
?>
<br>

<?php
    echo $this->formRow($form->get('nameS'));
?>
<br>
<?php
    echo $this->formRow($form->get('email'));
?>
<br>
<?php
    echo $this->formRow($form->get('typeS'));
?>

<?php
    echo $this->formRow($form->get('submit'));
?>


