<?php
// module/Album/view/album/album/index.phtml:

$title = 'Sửa thông tin người dùng';
$this->headTitle($title);
?>
<meta charset='utf-8'>
<div class="container">
    <h3><?php echo $title; ?></h3>
    <hr>
</div>

<?php
    $form->setAttribute('action',$this->url('auth',['action'=>'edit','acc'=>$id]));
    $form->prepare();
?>

<?php
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('acc'));
?>
<br>
<label>Mật khẩu</label>
<?php
    echo $this->formRow($form->get('pass'));
?>
<?php
    echo $this->formRow($form->get('id'));
?>
<br>
<label>Tên người dùng</label>
<?php
    echo $this->formRow($form->get('name'));
?>
<br>
<?php
    echo $this->formRow($form->get('submit'));
?>
